### ISSUE TITLE
Getting Exception in thread "main" java.lang.ExceptionInInitializerError

### ISSUE THREAD

**Issue by thotheolh** [xpring-eng/xpring4j#296]
I am trying to setup a Java Xpring for testing purposes.

`import java.math.BigInteger;
import io.xpring.common.XrplNetwork;
import io.xpring.xrpl.XrpClient;
import io.xpring.xrpl.XrpException;

public class Main {
	public static void main(String[] args) {
		try {
			XrpClient xrpClient = new XrpClient("test.xrp.xpring.io:50051", XrplNetwork.TEST);
			String address = "X7u4MQVhU2YxS4P9fWzQjnNuDRUkP3GM6kiVjTjcQgUU3Jr";
			BigInteger balance;
			balance = xrpClient.getBalance(address);
			System.out.println(balance);
		} catch (XrpException e) {
			e.printStackTrace();
		}
	}
}`

The above code is taken from the main wiki.

The results:

`Exception in thread "main" java.lang.ExceptionInInitializerError
	at io.xpring.xrpl.javascript.JavaScriptUtils.<init>(JavaScriptUtils.java:26)
	at io.xpring.xrpl.Utils.<clinit>(Utils.java:20)
	at io.xpring.xrpl.DefaultXrpClient.getBalance(DefaultXrpClient.java:104)
	at io.xpring.xrpl.ReliableSubmissionXrpClient.getBalance(ReliableSubmissionXrpClient.java:17)
	at io.xpring.xrpl.XrpClient.getBalance(XrpClient.java:51)
	at org.thothtrust.cryptocurrency.xrp.bridge.Main.main(Main.java:15)
Caused by: org.graalvm.polyglot.PolyglotException: SyntaxError: Invalid regular expression: /[Ö‘-Û¯Ûº-à£¿â€??-??-?ï¬?-ï·¿ï¹°-ï»¼]/: Range out of order in character class
	at <js>.:anonymous(/index.js:22)
	at <js>.:anonymous(/index.js:22)
	at <js>.r(/index.js:1)
	at <js>.:anonymous(/index.js:22)
	at <js>.r(/index.js:1)
	at <js>.:anonymous(/index.js:22)
	at <js>.r(/index.js:1)
	at <js>.:anonymous(/index.js:22)
	at <js>.r(/index.js:1)
	at <js>.:anonymous(/index.js:1)
	at <js>.:anonymous(/index.js:1)
	at <js>.:anonymous(/index.js:1)
	at <js>.:program(/index.js:1)
	at org.graalvm.polyglot.Context.eval(Context.java:345)
	at io.xpring.xrpl.javascript.JavaScriptLoader.<clinit>(JavaScriptLoader.java:49)
	... 6 more
`

The Maven dependency has been successfully included into the Eclipse IDE java project with Maven just for additional information. The maven dependency seems to be using xpring4j-6.0.2.jar.

**Comment by intelliot** [comment]
Xpring4j is no longer maintained. For Java XRPL support please see https://github.com/xrplf/xrpl4j
