### ISSUE TITLE
Unable to use in a multi threaded environment

### ISSUE THREAD

**Issue by timothyBrake** [xpring-eng/xpring4j#397]
When using the API in multiple threads, an exception is thrown.
Example code:
```
        Wallet fromSeedWallet = new Wallet("qwertyuiop123", true); // qwertyuiop123 > enter seed.

```
Throws this exception when used in multiple threads like e.g. batch jobs.

````
java.lang.IllegalStateException: Multi threaded access requested by thread Thread[scheduler_Worker-2,5,main] but is not allowed for language(s) js.
	at com.oracle.truffle.polyglot.PolyglotEngineException.illegalState(PolyglotEngineException.java:132) ~[truffle-api-20.2.0.jar:na]
	at com.oracle.truffle.polyglot.PolyglotContextImpl.throwDeniedThreadAccess(PolyglotContextImpl.java:660) ~[truffle-api-20.2.0.jar:na]
	at com.oracle.truffle.polyglot.PolyglotContextImpl.checkAllThreadAccesses(PolyglotContextImpl.java:563) ~[truffle-api-20.2.0.jar:na]
	at com.oracle.truffle.polyglot.PolyglotContextImpl.enterThreadChanged(PolyglotContextImpl.java:490) ~[truffle-api-20.2.0.jar:na]
	at com.oracle.truffle.polyglot.PolyglotEngineImpl.enter(PolyglotEngineImpl.java:1599) ~[truffle-api-20.2.0.jar:na]
	at com.oracle.truffle.polyglot.HostToGuestRootNode.execute(HostToGuestRootNode.java:89) ~[truffle-api-20.2.0.jar:na]
	at com.oracle.truffle.api.impl.DefaultCallTarget.call(DefaultCallTarget.java:99) ~[truffle-api-20.2.0.jar:na]
	at com.oracle.truffle.api.impl.DefaultRuntimeAccessor$DefaultRuntimeSupport.callProfiled(DefaultRuntimeAccessor.java:131) ~[truffle-api-20.2.0.jar:na]
	at com.oracle.truffle.polyglot.PolyglotValue$InteropValue.invoke(PolyglotValue.java:2809) ~[truffle-api-20.2.0.jar:na]
	at org.graalvm.polyglot.Value.invokeMember(Value.java:549) ~[graal-sdk-20.2.0.jar:na]
	at io.xpring.xrpl.javascript.JavaScriptWalletFactory.walletFromSeed(JavaScriptWalletFactory.java:85) ~[xpring4j-6.1.1.jar:na]
	at io.xpring.xrpl.Wallet.<init>(Wallet.java:35) ~[xpring4j-6.1.1.jar:na]
````

**Comment by intelliot** [comment]
Xpring4j is no longer maintained. For Java XRPL support please see https://github.com/xrplf/xrpl4j
