### ISSUE TITLE
Android device compatibility

### ISSUE THREAD

**Issue by html5cat** [xpring-eng/xpring4j#59]
Hi folks, it seems the SDK currently requires android api v.26+.
Do you know if it would be possible to extend it to 21 to support more devices?

Thank you!

**Comment by theotherian** [comment]
Not sure offhand but we can investigate what would be involved with supporting it 👍 

Thanks for raising the issue.

**Comment by sappenin** [comment]
Hi @html5cat - is there something specific about the SDK that is prompting your question? The only thing I can think of is the current requirement for Java8, but it [looks like](https://developer.android.com/studio/write/java8-support) Android v24 supports that. I don't think we're using many Java8 features, so it's possible that we could require a lesser Java version, but I wanted to make sure I understood what might need to be changed here in order to work with older Andoid versions.

**Comment by html5cat** [comment]
@sappenin yeah, I haven't dug deep into codebase to see what's limiting the version to be used.
Anything that can bring it closer to v21 is much appreciated!

**Comment by sappenin** [comment]
One thing that's needed here is the ability to build the library in a different profile for Android that uses OkHttp instead of Netty. See docs here: https://github.com/grpc/grpc-java#transport

@nkramer44

**Comment by mcungl** [comment]
@html5cat how did you actually manage to get it to run on Android? My build is crashing when trying to use it. 

`java.lang.NoSuchMethodError: No virtual method ensureClassInitialized(Ljava/lang/Class;)V in class Lsun/misc/Unsafe; or its super classes (declaration of 'sun.misc.Unsafe' appears in /apex/com.android.runtime/javalib/core-oj.jar)
        at com.oracle.truffle.api.library.LibraryFactory.ensureLibraryInitialized(LibraryFactory.java:337)
        at com.oracle.truffle.api.library.LibraryFactory.getUncached(LibraryFactory.java:318)
        at com.oracle.truffle.api.library.LibraryFactory.<init>(LibraryFactory.java:203)
        at com.oracle.truffle.api.interop.InteropLibraryGen.<init>(InteropLibraryGen.java:133)
        at com.oracle.truffle.api.interop.InteropLibraryGen.<clinit>(InteropLibraryGen.java:124)
        at java.lang.Class.classForName(Native Method)
        at java.lang.Class.forName(Class.java:454)
        at com.oracle.truffle.api.library.LibraryFactory.loadGeneratedClass(LibraryFactory.java:667)
        at com.oracle.truffle.api.library.LibraryFactory.resolveImpl(LibraryFactory.java:630)
        at com.oracle.truffle.api.library.LibraryFactory.resolve(LibraryFactory.java:623)
        at com.oracle.truffle.api.interop.InteropLibrary.<clinit>(InteropLibrary.java:1786)
        at com.oracle.truffle.api.interop.InteropLibrary.getFactory(InteropLibrary.java:1750)
        at com.oracle.truffle.polyglot.PolyglotValue.<clinit>(PolyglotValue.java:125)
        at com.oracle.truffle.polyglot.PolyglotValue.createHostNull(PolyglotValue.java:925)
        at com.oracle.truffle.polyglot.PolyglotImpl.initialize(PolyglotImpl.java:120)
        at org.graalvm.polyglot.impl.AbstractPolyglotImpl.setConstructors(AbstractPolyglotImpl.java:208)
        at org.graalvm.polyglot.Engine$1.run(Engine.java:724)
        at org.graalvm.polyglot.Engine$1.run(Engine.java:692)
        at java.security.AccessController.doPrivileged(AccessController.java:43)
        at org.graalvm.polyglot.Engine.initEngineImpl(Engine.java:692)
        at org.graalvm.polyglot.Engine.access$000(Engine.java:106)
        at org.graalvm.polyglot.Engine$ImplHolder.<clinit>(Engine.java:115)
        at org.graalvm.polyglot.Engine$ImplHolder.access$100(Engine.java:114)
        at org.graalvm.polyglot.Engine.getImpl(Engine.java:288)
        at org.graalvm.polyglot.Engine$Builder.build(Engine.java:526)
        at org.graalvm.polyglot.Context$Builder.build(Context.java:1587)
        at org.graalvm.polyglot.Context.create(Context.java:808)
        at io.xpring.xrpl.javascript.JavaScriptLoader.<clinit>(JavaScriptLoader.java:39)
        at io.xpring.xrpl.javascript.JavaScriptLoader.getContext(JavaScriptLoader.java:64)
        at io.xpring.xrpl.javascript.JavaScriptWalletFactory.<init>(JavaScriptWalletFactory.java:29)
        at io.xpring.xrpl.javascript.JavaScriptWalletFactory.<clinit>(JavaScriptWalletFactory.java:20)
        at io.xpring.xrpl.javascript.JavaScriptWalletFactory.get(JavaScriptWalletFactory.java:34)
        at io.xpring.xrpl.Wallet.<init>(Wallet.java:35)
        at io.xpring.xrpl.Wallet.<init>(Wallet.java:24)`

**Comment by html5cat** [comment]
@mcungl it's been a while since we last used it so things are probably different now!

**Comment by intelliot** [comment]
For those finding this issue in the future: Xpring4j is no longer maintained. For Java XRPL support please see https://github.com/xrplf/xrpl4j
